### PR TITLE
correct detection of GCC

### PR DESCRIPTION
**Pull request by slowriot**
GCC defines `__GNUC__`, not `GNUC.`

### CODE REVIEW

**Comment by a1batross** [comment]
+1.

**Comment by sjm324** [comment]
For what it's worth, you can cheat this a little bit while we wait for this to be brought in:

```
#ifdef __GNUC__
    #define GNUC
#endif
#include <openvr.h>
```

**Comment by jeremyselan** [comment]
Thanks, we've committed this internally and it will be updated in the next API release.

**Comment by slowriot** [comment]
Only a 9 month turnaround??  That's a record for this development team!

**Comment by Qix-** [comment]
Ahem. Two year turnaround. That's pretty steep, even for valve time.

**Comment by slowriot** [comment]
Oh good, I can finally stop holding my breath.

**Pull request closed without merging**
