### PR TITLE
VIVE Test

### PR DESCRIPTION
**Pull request by cylin**

### CODE REVIEW

**Comment by zao** [comment]
Hi, did you really intend to make this pull request against the upstream Valve `openvr` repository? Your PR seems to consist mostly of the commits of a private project and not really look like a curated PR for inclusion in the upstream repository.

**Comment by cylin** [comment]
Hi, sorry for the inconvenience, I carelessly pressed the pull request
button, I thought it will only affect forked branch. Please ignore it.
2016年12月20日 下午10:57於 "Lars Viklund" <notifications@github.com>寫道：

**Comment by javl** [comment]
@cylin You might want to close this pull request
https://help.github.com/articles/closing-a-pull-request/

**Comment by TTimo** [comment]
please stahp

**Pull request closed without merging**
