### PR TITLE
changed src/CmakeLists.txt to make openvr usable with add_subdirectory

### PR DESCRIPTION
**Pull request by EvilPictureBook**
This change let's you use openvr from a top level CMake file by using `add_subdirectory`

For example (with these changes) in my project's CmakeLists.txt I can:

```
...
add_subdirectory(openvr)

add_executable(test src/openvr_test.cpp)
target_link_libraries(test openvr_api ${CMAKE_DL_LIBS})
...
```

### CODE REVIEW

**Comment by godbyk** [comment]
@JoeLudwig This PR allows us to use the `openvr` git repository as a submodule. The changes still allow for OpenVR to be built in standalone. Any chance we can get this merged in? Thanks!

**Comment by Bobo1239** [comment]
Probably also want to change `CMAKE_{LIBRARY,ARCHIVE,RUNTIME}_OUTPUT_DIRECTORY` in `CMakeLists.txt` (in the OpenVR root directory) to use `CMAKE_CURRENT_SOURCE_DIR` so the output doesn't land in the top-level project.

**Comment by EvilPictureBook** [comment]
That's a good point @Bobo1239, I added the change.

@JoeLudwig, @jeremyselan any chance to merge this in?

**Comment by natbro** [comment]
Thanks for the PR, it's a good fix & will be in the next update to the OpenVR SDK.

**Comment by EvilPictureBook** [comment]
@natbro I saw that there's a new release of OpenVR, but the cmake changes didn't make it in. Anything else I could do to help?

**Comment by JoeLudwig** [comment]
When Nat wrote "next" he meant "an upcoming". The change is in the current SteamVR beta and will be in the actual next* SDK update. There's a pipeline from our main branch to the SDK that flows through the beta even for changes like this that don't actually affect the beta.

* this time for sure. I see the change in our rel branch which is where the next SDK will come from.

**Comment by EvilPictureBook** [comment]
@JoeLudwig thanks for the explanation, that makes sense.

**Comment by n8vm** [comment]
Thanks!!

**Pull request closed without merging**
